### ISSUE TITLE
YOLO34py-gpu install error

### ISSUE THREAD

**Issue by mozi22** [madhawav/YOLO3-4-Py#65] opened 2019-02-25 17:30 UTC
Hi I am trying to install darknet with `pip install yolo34py-gpu` but I get the following error. 

I've already checked other threads where everyone has some problem or the other but I am not sure what is the problem in my case. Can you please help out.

I'm using cuda-9.0, gcc 5.4.0 and nvcc 9.0. 

Not sure what exactly is the problem.

```
Collecting yolo34py-gpu
  Using cached https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz
Requirement already satisfied: cython>=0.27 in /home/muazzam/anaconda3/lib/python3.7/site-packages (from yolo34py-gpu) (0.29.2)
Requirement already satisfied: requests in /home/muazzam/anaconda3/lib/python3.7/site-packages (from yolo34py-gpu) (2.21.0)
Requirement already satisfied: numpy in /home/muazzam/anaconda3/lib/python3.7/site-packages (from yolo34py-gpu) (1.15.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/muazzam/anaconda3/lib/python3.7/site-packages (from requests->yolo34py-gpu) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/muazzam/anaconda3/lib/python3.7/site-packages (from requests->yolo34py-gpu) (2018.11.29)
Requirement already satisfied: idna<2.9,>=2.5 in /home/muazzam/anaconda3/lib/python3.7/site-packages (from requests->yolo34py-gpu) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/muazzam/anaconda3/lib/python3.7/site-packages (from requests->yolo34py-gpu) (3.0.4)
Building wheels for collected packages: yolo34py-gpu
  Running setup.py bdist_wheel for yolo34py-gpu ... error
  Complete output from command /home/muazzam/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kbbiymmd/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nwi24g73 --python-tag cp37:
  INFO:root:DARKNET_HOME is set: /home/muazzam/darknet
  /home/muazzam/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
    normalized_version,
  running bdist_wheel
  running build
  INFO:root:Copying libdarknet.so from /home/muazzam/darknet
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.7/__libdarknet
  running egg_info
  writing yolo34py_gpu.egg-info/PKG-INFO
  writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
  writing requirements to yolo34py_gpu.egg-info/requires.txt
  writing top-level names to yolo34py_gpu.egg-info/top_level.txt
  reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.7/__libdarknet
  running build_ext
  skipping 'pydarknet.cpp' Cython extension (up-to-date)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -B /home/muazzam/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/muazzam/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/muazzam/darknet/include -I/home/muazzam/darknet/src -I/home/muazzam/anaconda3/include/python3.7m -c pydarknet.cpp -o build/temp.linux-x86_64-3.7/pydarknet.o
  gcc: error: : No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for yolo34py-gpu
  Running setup.py clean for yolo34py-gpu
Failed to build yolo34py-gpu
Installing collected packages: yolo34py-gpu
  Running setup.py install for yolo34py-gpu ... error
    Complete output from command /home/muazzam/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kbbiymmd/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ldgi_q2j/install-record.txt --single-version-externally-managed --compile:
    INFO:root:DARKNET_HOME is set: /home/muazzam/darknet
    /home/muazzam/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:470: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      normalized_version,
    running install
    running build
    INFO:root:Copying libdarknet.so from /home/muazzam/darknet
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.7/__libdarknet
    running egg_info
    writing yolo34py_gpu.egg-info/PKG-INFO
    writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
    writing requirements to yolo34py_gpu.egg-info/requires.txt
    writing top-level names to yolo34py_gpu.egg-info/top_level.txt
    reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pydarknet.cpp'
    writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.7/__libdarknet
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    /home/muazzam/anaconda3/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-kbbiymmd/yolo34py-gpu/pydarknet.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -B /home/muazzam/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/muazzam/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/muazzam/darknet/include -I/home/muazzam/darknet/src -I/home/muazzam/anaconda3/include/python3.7m -c pydarknet.cpp -o build/temp.linux-x86_64-3.7/pydarknet.o
    gcc: error: : No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/muazzam/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kbbiymmd/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ldgi_q2j/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-kbbiymmd/yolo34py-gpu/

```

**Comment by madhawav** [comment] 2019-02-26 08:54
Hi
Recently I came across a similar case due to python3-dev missing. Can you try the following?
`sudo apt-get install python3-dev`

**Comment by mozi22** [comment] 2019-02-26 13:10
Thanks, that seemed to work but now I get a different error. Can you please take a look.

```
Collecting yolo34py-gpu
  Using cached https://files.pythonhosted.org/packages/dc/a3/12c668e54109c5469a8312d757b357dda0b2efc2150043b76b58f6ba75c3/yolo34py-gpu-0.1rc12.tar.gz
Requirement already satisfied: cython>=0.27 in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from yolo34py-gpu) (0.29.5)
Requirement already satisfied: requests in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from yolo34py-gpu) (2.21.0)
Requirement already satisfied: numpy in /home/muazzam/.local/lib/python3.6/site-packages (from yolo34py-gpu) (1.16.1)
Requirement already satisfied: idna<2.9,>=2.5 in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from requests->yolo34py-gpu) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from requests->yolo34py-gpu) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from requests->yolo34py-gpu) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages (from requests->yolo34py-gpu) (2018.11.29)
Building wheels for collected packages: yolo34py-gpu
  Building wheel for yolo34py-gpu (setup.py) ... error
  Complete output from command /home/muazzam/.conda/envs/precitaste/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ebtwwte4/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-5mj77at9 --python-tag cp36:
  INFO:root:DARKNET_HOME is set: /home/muazzam/darknet
  /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
    normalized_version,
  running bdist_wheel
  running build
  INFO:root:Copying libdarknet.so from /home/muazzam/darknet
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/__libdarknet
  copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.6/__libdarknet
  running egg_info
  writing yolo34py_gpu.egg-info/PKG-INFO
  writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
  writing requirements to yolo34py_gpu.egg-info/requires.txt
  writing top-level names to yolo34py_gpu.egg-info/top_level.txt
  reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
  copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.6/__libdarknet
  running build_ext
  skipping 'pydarknet.cpp' Cython extension (up-to-date)
  building 'pydarknet' extension
  creating build/temp.linux-x86_64-3.6
  gcc -pthread -B /home/muazzam/.conda/envs/precitaste/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include -I/home/muazzam/darknet/include -I/home/muazzam/darknet/src -I/home/muazzam/.conda/envs/precitaste/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pydarknet.cpp:580:
  /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^
  pydarknet.cpp: In function ‘PyObject* __pyx_pf_9pydarknet_5Image_2show_image(__pyx_obj_9pydarknet_Image*, char*)’:
  pydarknet.cpp:2232:46: error: too few arguments to function ‘int show_image(image, const char*, int)’
     show_image(__pyx_v_self->img, __pyx_v_title);
                                                ^
  In file included from bridge.h:9:0,
                   from pydarknet.cpp:586:
  /home/muazzam/darknet/include/darknet.h:709:5: note: declared here
   int show_image(image p, const char *name, int ms);
       ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for yolo34py-gpu
  Running setup.py clean for yolo34py-gpu
Failed to build yolo34py-gpu
Installing collected packages: yolo34py-gpu
  Running setup.py install for yolo34py-gpu ... error
    Complete output from command /home/muazzam/.conda/envs/precitaste/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ebtwwte4/yolo34py-gpu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-79wbadio/install-record.txt --single-version-externally-managed --compile:
    INFO:root:DARKNET_HOME is set: /home/muazzam/darknet
    /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.1.rc12' to '0.1rc12'
      normalized_version,
    running install
    running build
    INFO:root:Copying libdarknet.so from /home/muazzam/darknet
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/__libdarknet
    copying __libdarknet/__init__.py -> build/lib.linux-x86_64-3.6/__libdarknet
    running egg_info
    writing yolo34py_gpu.egg-info/PKG-INFO
    writing dependency_links to yolo34py_gpu.egg-info/dependency_links.txt
    writing requirements to yolo34py_gpu.egg-info/requires.txt
    writing top-level names to yolo34py_gpu.egg-info/top_level.txt
    reading manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pydarknet.cpp'
    writing manifest file 'yolo34py_gpu.egg-info/SOURCES.txt'
    copying __libdarknet/libdarknet.so -> build/lib.linux-x86_64-3.6/__libdarknet
    running build_ext
    cythoning pydarknet.pyx to pydarknet.cpp
    /home/muazzam/.conda/envs/precitaste/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-ebtwwte4/yolo34py-gpu/pydarknet.pxd
      tree = Parsing.p_module(s, pxd, full_module_name)
    building 'pydarknet' extension
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -B /home/muazzam/.conda/envs/precitaste/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CV=0 -I/home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include -I/home/muazzam/darknet/include -I/home/muazzam/darknet/src -I/home/muazzam/.conda/envs/precitaste/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o -I/usr/include/python3.5m -I/usr/include/x86_64-linux-gnu/python3.5m
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pydarknet.cpp:607:
    /home/muazzam/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^
    pydarknet.cpp: In function ‘PyObject* __pyx_pf_9pydarknet_5Image_2show_image(__pyx_obj_9pydarknet_Image*, char*)’:
    pydarknet.cpp:2327:46: error: too few arguments to function ‘int show_image(image, const char*, int)’
       show_image(__pyx_v_self->img, __pyx_v_title);
                                                  ^
    In file included from bridge.h:9:0,
                     from pydarknet.cpp:613:
    /home/muazzam/darknet/include/darknet.h:709:5: note: declared here
     int show_image(image p, const char *name, int ms);
         ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

```

**Comment by madhawav** [comment] 2019-03-03 06:37
Hi,
This issue is caused by a new parameter added to method show_image in Darknet. It has been already fixed in the code in the master branch. However, the updated version is not yet released to PIP. 

Can you install YOLO3-4-Py by compiling the code as described in the readme section?

**Closed** 2019-05-03 04:17 UTC

**Comment by milliema** [comment] 2019-09-18 10:13
> Hi
> Recently I came across a similar case due to python3-dev missing. Can you try the following?
> `sudo apt-get install python3-dev`

Thanks! Solved my problem!
