### ISSUE TITLE
Unable to import pydarknet

### ISSUE THREAD

**Issue by Ntweat** [madhawav/YOLO3-4-Py#1] opened 2018-04-04 06:39 UTC
Hi I am getting following error

`>>> import pydarknet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ntweat/Desktop/yolo/PyYOLOV3/pydarknet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv8fastFreeEPv
>>> `

Thanks for the wrapper

**Comment by madhawav** [comment] 2018-04-08 03:26
Hi,
Thank you for raising the issue. 
1) Can I know the operating system you work on? 
2) Did you clone and compile the darknet repository as mentioned?

**Comment by madhawav** [comment] 2018-04-08 09:03
@Ntweat, can I know the version of OpenCV you used? 

**I managed to reproduce this issue by compiling with OpenCV 3.4.1. It can be resolved by compiling using Open CV 3.4.0.**

In fact, it is mentioned [here](https://github.com/pjreddie/darknet/issues/502) that darknet does not work with OpenCV 3.4.1 due to an issue in Open CV 3.4.1 C API. 

On a side note, you have to compile Darknet with OpenCV enabled as explained [here](https://pjreddie.com/darknet/install/#cuda). I have forgotten to mention this step at the Readme. 

Does compiling with OpenCV 3.4.0 solve your issue?
Thanks

**Comment by justinas-kazanavicius** [comment] 2018-04-10 00:14
I'm getting the exact same error. I'm sure I have opencv 3.4.0 because I get this if I check my version in python: 
```
>>> import cv2
>>> cv2.__version__
'3.4.0'
```

Also, if I run darknet test:
`./darknet imtest data/eagle.jpg`
it works just as intended.

Also, when using setup.py I get:

```
python3 setup.py build_ext --inplace
/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
skipping 'pydarknet.cpp' Cython extension (up-to-date)
building 'pydarknet' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/home/justin/Projects/comp3931/darknet/include -I/home/justin/Projects/comp3931/darknet/src -I/usr/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o -I/usr/include/opencv -I/usr/include/python3.6m
In file included from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pydarknet.cpp:539:
/usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/home/justin/Projects/comp3931/darknet/include -I/home/justin/Projects/comp3931/darknet/src -I/usr/include/python3.6m -c bridge.cpp -o build/temp.linux-x86_64-3.6/bridge.o -I/usr/include/opencv -I/usr/include/python3.6m
g++ -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none build/temp.linux-x86_64-3.6/pydarknet.o build/temp.linux-x86_64-3.6/bridge.o -L/home/justin/Projects/comp3931/darknet -L/usr/lib64 -ldarknet -lm -lpthread -lpython3.6m -o /home/justin/Projects/comp3931/YOLO3-4-Py/pydarknet.cpython-36m-x86_64-linux-gnu.so -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_datasets -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_line_descriptor -lopencv_optflow -lopencv_video -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_surface_matching -lopencv_text -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core -lpython3.6m
/usr/bin/ld: cannot find -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_datasets -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_line_descriptor -lopencv_optflow -lopencv_video -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_surface_matching -lopencv_text -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```
Maybe this might be the problem? If so, how can I fix it? I use Linux (Fedora).

**Comment by abossenbroek** [comment] 2018-04-10 00:16
Based on the `ld` error your `LD_LIBRARY_PATH` variable seems not to point to a location where opencv is installed. How did you install opencv?

**Comment by justinas-kazanavicius** [comment] 2018-04-10 10:35
@abossenbroek @madhawav

I've just reinstalled OpenCV-3.4.0 in ~/Libs/opencv-3.4.0
.so files are in ~/Libs/opencv-3.4.0/build/lib
I've added this path to LD_LIBRARY_PATH
Ran `ldconfig`. And it still throws the same error...

```
$ env | grep '^LD_LIBRARY_PATH'           
LD_LIBRARY_PATH=/home/justin/Projects/darknet:/home/justin/Libs/opencv-3.4.0/build/lib
```

```
$ ls /home/justin/Libs/opencv-3.4.0/build/lib | grep "libopencv*"
libopencv_calib3d_pch_dephelp.a
libopencv_calib3d.so
libopencv_calib3d.so.3.4
libopencv_calib3d.so.3.4.0
libopencv_core_pch_dephelp.a
libopencv_core.so
libopencv_core.so.3.4
libopencv_core.so.3.4.0
libopencv_dnn_pch_dephelp.a
libopencv_dnn.so
libopencv_dnn.so.3.4
libopencv_dnn.so.3.4.0
libopencv_features2d_pch_dephelp.a
libopencv_features2d.so
libopencv_features2d.so.3.4
libopencv_features2d.so.3.4.0
libopencv_flann_pch_dephelp.a
libopencv_flann.so
libopencv_flann.so.3.4
libopencv_flann.so.3.4.0
libopencv_highgui_pch_dephelp.a
libopencv_highgui.so
libopencv_highgui.so.3.4
libopencv_highgui.so.3.4.0
libopencv_imgcodecs_pch_dephelp.a
libopencv_imgcodecs.so
libopencv_imgcodecs.so.3.4
libopencv_imgcodecs.so.3.4.0
libopencv_imgproc_pch_dephelp.a
libopencv_imgproc.so
libopencv_imgproc.so.3.4
libopencv_imgproc.so.3.4.0
libopencv_ml_pch_dephelp.a
libopencv_ml.so
libopencv_ml.so.3.4
libopencv_ml.so.3.4.0
libopencv_objdetect_pch_dephelp.a
libopencv_objdetect.so
libopencv_objdetect.so.3.4
libopencv_objdetect.so.3.4.0
libopencv_perf_calib3d_pch_dephelp.a
libopencv_perf_core_pch_dephelp.a
libopencv_perf_dnn_pch_dephelp.a
libopencv_perf_features2d_pch_dephelp.a
libopencv_perf_imgcodecs_pch_dephelp.a
libopencv_perf_imgproc_pch_dephelp.a
libopencv_perf_objdetect_pch_dephelp.a
libopencv_perf_photo_pch_dephelp.a
libopencv_perf_stitching_pch_dephelp.a
libopencv_perf_superres_pch_dephelp.a
libopencv_perf_videoio_pch_dephelp.a
libopencv_perf_video_pch_dephelp.a
libopencv_photo_pch_dephelp.a
libopencv_photo.so
libopencv_photo.so.3.4
libopencv_photo.so.3.4.0
libopencv_shape_pch_dephelp.a
libopencv_shape.so
libopencv_shape.so.3.4
libopencv_shape.so.3.4.0
libopencv_stitching_pch_dephelp.a
libopencv_stitching.so
libopencv_stitching.so.3.4
libopencv_stitching.so.3.4.0
libopencv_superres_pch_dephelp.a
libopencv_superres.so
libopencv_superres.so.3.4
libopencv_superres.so.3.4.0
libopencv_test_calib3d_pch_dephelp.a
libopencv_test_core_pch_dephelp.a
libopencv_test_dnn_pch_dephelp.a
libopencv_test_features2d_pch_dephelp.a
libopencv_test_flann_pch_dephelp.a
libopencv_test_highgui_pch_dephelp.a
libopencv_test_imgcodecs_pch_dephelp.a
libopencv_test_imgproc_pch_dephelp.a
libopencv_test_ml_pch_dephelp.a
libopencv_test_objdetect_pch_dephelp.a
libopencv_test_photo_pch_dephelp.a
libopencv_test_shape_pch_dephelp.a
libopencv_test_stitching_pch_dephelp.a
libopencv_test_superres_pch_dephelp.a
libopencv_test_videoio_pch_dephelp.a
libopencv_test_video_pch_dephelp.a
libopencv_test_videostab_pch_dephelp.a
libopencv_ts.a
libopencv_ts_pch_dephelp.a
libopencv_videoio_pch_dephelp.a
libopencv_videoio.so
libopencv_videoio.so.3.4
libopencv_videoio.so.3.4.0
libopencv_video_pch_dephelp.a
libopencv_video.so
libopencv_video.so.3.4
libopencv_video.so.3.4.0
libopencv_videostab_pch_dephelp.a
libopencv_videostab.so
libopencv_videostab.so.3.4
libopencv_videostab.so.3.4.0
```

**Comment by madhawav** [comment] 2018-04-10 11:58
@justinas-kazanavicius Did you follow the `make install` step in OpenCV installation? 

It seems pkg-config is not updated after the new installation of OpenCV. For example, pkg-config lists a result called `-lopencv_line_descriptor` but `libopencv_line_descriptor` is not present in your installation directory.

**Comment by justinas-kazanavicius** [comment] 2018-04-10 12:49
@madhawav Saw your comment just after fixing it. You're right, I did not. 

I fixed it by completely uninstalling all opencv packages on my computer. Re-installing OpenCV-3.4.0, using [these](https://github.com/madhawav/YOLO3-4-Py/blob/master/tools/install_opencv34.sh) instructions from this repo. And then running `export PKG_CONFIG_PATH=/home/justin/Libs/opencv-3.4.0/build/unix-install`. Then I used `make` on darknet again, and after that YOLO3-4-Py/setup.py was working as intended.

What confused me was the other packages of opencv that I had on my computer. They allowed me to compile darknet sucessfully, and that made me think my opencv-3.4.0 installation was successful.

Thanks for the help!

**Comment by justinas-kazanavicius** [comment] 2018-04-10 13:12
However... even though it installs, it still doesn't run. I get
```
Traceback (most recent call last):
  File "webcam_test.py", line 3, in <module>
    import pydarknet
ImportError: /home/justin/Projects/darknet/libdarknet.so: undefined symbol: cvWaitKey

```

**Comment by abossenbroek** [comment] 2018-04-10 13:34
It looks like your executable cannot resolve your OpenCV libraries. Try adding the path with your opencv install to `/etc/ld.so.conf.d` dir following steps outlined [here](https://www.cyberciti.biz/faq/linux-setting-changing-library-path/). 

BTW, you may want to install your libraries in `/usr/local/` instead of your home dir.

**Comment by madhawav** [comment] 2018-04-10 13:35
@justinas-kazanavicius Did you do a clean build on darknet after re-installing OpenCV ? 
```
cd darknet_home
make clean
make
```

Maybe your re-using the old libdarknet.so file which you made with previous installation of OpenCV. It would probably fail to link with new installation of OpenCV.

**Comment by justinas-kazanavicius** [comment] 2018-04-10 23:38
@abossenbroek @
I did, same error. It seems that libraries are recognised:
```
$ ldconfig -v | grep opencv
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
/home/justin/Libs/opencv-3.4.0/build/lib:
	libopencv_core.so.3.4 -> libopencv_core.so.3.4.0
	libopencv_imgcodecs.so.3.4 -> libopencv_imgcodecs.so.3.4.0
	libopencv_stitching.so.3.4 -> libopencv_stitching.so.3.4.0
	libopencv_flann.so.3.4 -> libopencv_flann.so.3.4.0
	libopencv_shape.so.3.4 -> libopencv_shape.so.3.4.0
	libopencv_videoio.so.3.4 -> libopencv_videoio.so.3.4.0
	libopencv_video.so.3.4 -> libopencv_video.so.3.4.0
	libopencv_dnn.so.3.4 -> libopencv_dnn.so.3.4.0
	libopencv_imgproc.so.3.4 -> libopencv_imgproc.so.3.4.0
	libopencv_features2d.so.3.4 -> libopencv_features2d.so.3.4.0
	libopencv_photo.so.3.4 -> libopencv_photo.so.3.4.0
	libopencv_highgui.so.3.4 -> libopencv_highgui.so.3.4.0
	libopencv_superres.so.3.4 -> libopencv_superres.so.3.4.0
	libopencv_calib3d.so.3.4 -> libopencv_calib3d.so.3.4.0
	libopencv_videostab.so.3.4 -> libopencv_videostab.so.3.4.0
	libopencv_ml.so.3.4 -> libopencv_ml.so.3.4.0
	libopencv_objdetect.so.3.4 -> libopencv_objdetect.so.3.4.0
ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```

@madhawav 
I did a fresh download and `make` of darknet just after re-installing opencv. I've just done `make clean` and `make` and its the same result...


I've just tried to remove of yolo3-4py and cloned it again. Now when running setup.py, I get:
```
python3 setup.py build_ext --inplace
/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running build_ext
skipping 'pydarknet.cpp' Cython extension (up-to-date)
building 'pydarknet' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/home/justin/Projects/darknet/include -I/home/justin/Projects/darknet/src -I/usr/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o  -I/usr/include/python3.6m
gcc: error: : No such file or directory
error: command 'gcc' failed with exit status 1
```
Paths seem to be set up well.
```
env | grep darknet
DARKNET_HOME=/home/justin/Projects/darknet
LD_LIBRARY_PATH=:/home/justin/Projects/darknet:/home/justin/Libs/opencv-3.4.0/build/lib
```

**Comment by abossenbroek** [comment] 2018-04-11 00:05
run `sudo ldconfig` to fix the permission issue

**Comment by madhawav** [comment] 2018-04-11 03:27
@justinas-kazanavicius
`gcc: error: : No such file or directory` seems kind of strange. Usually these kind of gcc errors are reported in the format `gcc:error:[file_name]:No such file or directory`. But in your case, the results suggests that gcc is looking for a file with a [space] name. 
I will look further into this and get back to you.

**Comment by madhawav** [comment] 2018-04-12 03:45
@justinas-kazanavicius can I know the version of Fedora you use?
Also, have you made any progress following what @abossenbroek said.

Thanks

**Comment by justinas-kazanavicius** [comment] 2018-04-12 08:34
@madhawav 
- It compiles and works perfectly, thank you! I will use this branch for now then.
- Fedora 27
- You mean running `sudo ldconfig`? Yeah, nothing changes.

**Comment by madhawav** [comment] 2018-04-12 09:12
@justinas-kazanavicius Glad to here!

 I've just managed to re-produce the error `undefined symbol: _ZN2cv8fastFreeEPv` by compiling darknet without having OpenCV flag set. (That means without setting OpenCV=1 in makefile of darknet.) 

Could that be the reason why you couldn't use the code from master branch? 

Also, I will send you a performance comparison between two branches soon.

**Comment by madhawav** [comment] 2018-04-12 09:31
@justinas-kazanavicius 
Efficiency readings taken on webcam_test.py

__Master Branch__
```
('Internal Time:', 0.08028554916381836, ':', 0.06916772574186325)
Total Time: 0.08295273780822754 : 0.07138648479168823
Efficiency: 0.9689190600111561
('Internal Time:', 0.06472063064575195, ':', 0.06827830523252487)
Total Time: 0.06650710105895996 : 0.07041060804514258
Efficiency: 0.9697161710171481
('Internal Time:', 0.06425833702087402, ':', 0.06747431308031082)
Total Time: 0.06623339653015137 : 0.06957516574214434
Efficiency: 0.969804561161671
```

__direct-numpy-to-darknet-image-conversion Branch__
```
('Internal Time:', 0.06983137130737305, ':', 0.06395943462848663)
Total Time: 0.07549619674682617 : 0.0697771673644012
Efficiency: 0.9166241199570011
('Internal Time:', 0.062108755111694336, ':', 0.06358929723501205)
Total Time: 0.06771492958068848 : 0.06936471980765867
Efficiency: 0.9167383276590567
('Internal Time:', 0.06394815444946289, ':', 0.06366106867790222)
Total Time: 0.07091593742370605 : 0.06967496333086814
Efficiency: 0.9136864324648796
```

- Internal Time: Time taken by native YOLO3 call internally.
- Total Time: internal time + additional cost of wrapper
- Efficiency: Average Inernal Time / Average Total Time

__Internal time measurement at pydarknet.pyx__
```python
        internal_start = time.time()
        network_predict_image(self.net, image.img)
        dets = get_network_boxes(self.net, image.img.w, image.img.h, thresh, hier_thresh, <int*>0, 0, pnum)

        num = pnum[0]
        if (nms > 0):
            do_nms_obj(dets, num, self.meta.classes, nms)

        internal_end = time.time()
        self.average_internal_time = self.average_internal_time * 0.8 + (internal_end-internal_start) * 0.2
        print("Internal Time:",internal_end-internal_start, ":", self.average_internal_time)
```

__Total time measurement at webcam_test.py__
```python
            start_time = time.time()

            # Only measure the time taken by YOLO and API Call overhead

            dark_frame = Image(frame)
            results = net.detect(dark_frame)
            del dark_frame

            end_time = time.time()
            average_time = average_time * 0.8 + (end_time-start_time) * 0.2

            print("Total Time:", end_time-start_time, ":", average_time)
            print("Efficiency:", net._get_average_time()/average_time)
```

**Comment by justinas-kazanavicius** [comment] 2018-04-12 12:27
Found the issue!

Previously before compiling darknet, I executed `export PKG_CONFIG_PATH=/home/justin/Libs/opencv-3.4.0/build/unix-install` in my terminal, but I did not add it to my `~/.bash_profile`, then I guess I used another terminal to continue with YOLO3-4-Py installation and because of that `PKG_CONFIG_PATH` got reset.

I've added `export PKG_CONFIG_PATH=/home/justin/Libs/opencv-3.4.0/build/unix-install` to my `~/.bash_profile` now and it's working fine with master branch!

Thanks for all your help @madhawav and @abossenbroek !

**Comment by madhawav** [comment] 2018-04-13 03:00
Glad to help @justinas-kazanavicius. 
Will close this issue then. Re-open if you encounter any similar issues.

Happy coding!

**Closed by madhawav** 2018-04-13 03:00 UTC
Labels: help wanted, question

**Comment by maylad31** [comment] 2018-11-28 12:46
hi i am getting ImportError: /home/step/YOLO3P/pydarknet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv8fastFreeEPv
I have tried some things mentioned here
but i don't want to uninstall my opencv
I have installed opencv 3.4.0 from source
