### ISSUE TITLE
Installation fails 

### ISSUE THREAD

**Issue by lozuwa** [madhawav/YOLO3-4-Py#32] opened 2018-09-04 22:29 UTC
OS: Ubuntu 16.04
Notes: I used python setup.py clean as it worked a few weeks ago. Though now it does not work. 
Error:
INFO:root:Darknet building successful
INFO:root:Moving to /home/nvd/Downloads/YOLO3-4-Py/__libdarknet/libdarknet.so
skipping 'pydarknet.cpp' Cython extension (up-to-date)
building 'pydarknet' extension
gcc -pthread -B /home/nvd/anaconda3/envs/tensorflow_10/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_GPU=0 -DUSE_CV=0 -I/home/nvd/anaconda3/envs/tensorflow_10/lib/python3.6/site-packages/numpy/core/include -I/tmp/darknet/darknet-yolo34py-intergration-nogpu-v2/include -I/tmp/darknet/darknet-yolo34py-intergration-nogpu-v2/src -I/home/nvd/anaconda3/envs/tensorflow_10/include/python3.6m -c pydarknet.cpp -o build/temp.linux-x86_64-3.6/pydarknet.o 
gcc: error: : No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by madhawav** [comment] 2018-09-05 02:31
Hi,
Can you get a new clone of the project and try again? Also delete the darknet folder in /tmp of your system. 

(The line `skipping 'pydarknet.cpp' Cython extension (up-to-date) ` suggests that installation is using some of the old files from a previous installation)

**Comment by lozuwa** [comment] 2018-09-05 14:12
Thanks,
1. One way to install.
python setup.py clean 
python setup.py install

2. Another way to install. 
pip install yolo34py-gpu

Both installations give the same error.

**Comment by madhawav** [comment] 2018-09-17 16:06
Hi, 
Did you manage to find any solution for this issue? 

It seems the reason for the issue is skipping of building of Cython extensions ( as explained by `skipping 'pydarknet.cpp' Cython extension (up-to-date)`) but that could happen only if a previously built `pydarknet.cpp` is left in the source code. If such a file exist, can you delete it and re-run the installation?

**Comment by madhawav** [comment] 2018-10-05 16:06
Closing due to absence of response.

**Closed** 2018-10-05 16:06 UTC
